### ISSUE TITLE
Publishing add-on to catalog

### ISSUE THREAD

**Issue by danamag** [kianjomi/RARBG-TorrentAPI-Stremio#1]
Hi, I saw you posted to StremioAddons but then your user got shadow banned. :))

You can publish your add-on on the web ui:
https://stremio.github.io/stremio-publish-addon/index.html

You'll need to enter your manifest url there, in your case it should be:
https://rarbg-torrentapi-stremio.herokuapp.com/manifest.json

Good luck!

**Comment by kianjomi** [comment]
Thanks,
I create a new account in reddit.
