### ISSUE TITLE
No results in the last 7 days

### ISSUE THREAD

**Issue by springroll-xx** [kianjomi/RARBG-TorrentAPI-Stremio#2]
As reported via Reddit, the add-on hasn't been producing any results in the last 7 days.  Hopefully it's not something that the author will have to constantly fix due to RARBG always updating something on their end

**Comment by danamag** [comment]
Yeah, I can't l'm getting "application error" if i even try to load the manifest url:
http://rarbg-torrentapi-stremio.herokuapp.com/manifest.json

**Comment by kianjomi** [comment]
Web Server Overload, sorry!

**Comment by springroll-xx** [comment]
Kianjomi - You are back! Yay. Thanks for looking after this add-on.  We love it and appreciate all the work you are doing with it. Is web server overload the reason the issue?

**Comment by kianjomi** [comment]
Hi,
Install new version: https://add-on.rarbg-torrentapi-stremio.xyz
